
<?php

echo '<nav><p>
        <span class="menu"><a href="index.php">Home</a></span>
		<span class="menu"><a href="menu.php">Menu</a></span>
		<span class="menu"><a href="enquire.php">Dine-in</a></span>
		<span class="menu"><a href="takeaway.php">Take-away</a></span>
		<span class="menu"><a href="about.php">About</a></span>
		<span class="menu"><a href="includes/manager.php">Manage</a></span></p>
    </nav>';
	
?>